
server:
  port: 3344
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Zzwenm/spring-cloud-config.git  #github上面的git仓库
          #搜索目录
          search-paths:
            - spring-cloud-config
      #读取分支
      label: master
  #rabbitmq相关配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

#rabbitmq相关配置
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: 'bus-refresh'